all:
  children:
    siem:
      hosts:
        WAZ-ALT-01: { ansible_host: 10.0.1.10, wazuh_role: master }
        WAZ-ALT-02: { ansible_host: 10.0.1.11, wazuh_role: worker }
        WAZ-ALT-03: { ansible_host: 10.0.1.12, wazuh_role: indexer }
    monitoring:
      hosts:
        MON-ALT-01: { ansible_host: 10.0.2.10 }
    cicd:
      hosts:
        GIT-ALT-01: { ansible_host: 10.0.3.10 }
        DSO-ALT-01: { ansible_host: 10.0.3.11 }
        ANS-ALT-01: { ansible_host: 10.0.3.12 }
