---
# Installation et configuration du moteur Docker
- name: Installer les dépendances
  ansible.builtin.package:
    name: [ca-certificates, curl, gnupg]
    state: present

- name: Installer Docker CE
  ansible.builtin.package:
    name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
    state: present

- name: Démarrer et activer Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
